name: breve
description: Order ahead. Skip the line.
version: 0.0.2
homepage: http://getbreve.com

dependencies:
  flutter:
    sdk: flutter
  provider: ^2.0.0
  firebase_auth: ^0.14.0+5
  firebase_database: ^3.0.7
  firebase_core: ^0.4.3+2
  cloud_firestore: ^0.13.0+1
  stripe_payment: ^1.0.4
  uuid: ^2.0.2
  mask_text_input_formatter: ^1.0.6
  flutter_credit_card: ^0.1.3
  intl: ^0.16.0
  bubble_tab_indicator: ^0.1.4
  firebase_messaging: ^6.0.9
  dashed_container: ^1.0.1
  
flutter_icons:
  android: true 
  ios: true
  image_path: "assets/breveicon2.png"

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.otf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-Light.otf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-Medium.otf
          weight: 600
        - asset: assets/fonts/Montserrat-MediumItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400
        - asset: assets/fonts/Montserrat-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Montserrat-Thin.otf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.otf
          weight: 100
          style: italic

 
